package MindMap.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.nodeEditor.cellProviders.AbstractCellListHandler;
import jetbrains.mps.lang.editor.cellProviders.RefNodeListHandler;
import jetbrains.mps.smodel.action.NodeFactoryManager;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.openapi.editor.menus.transformation.SNodeLocation;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.nodeEditor.cellActions.CellAction_DeleteNode;
import jetbrains.mps.openapi.editor.cells.DefaultSubstituteInfo;
import jetbrains.mps.nodeEditor.cellMenu.SChildSubstituteInfo;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.editor.runtime.impl.cellActions.CellAction_DeleteSmart;

/*package*/ class Mindmap_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Mindmap_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_yx4xk1_a();
  }

  private EditorCell createCollection_yx4xk1_a() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_yx4xk1_a");
    editorCell.setBig(true);
    editorCell.setCellContext(getCellFactory().getCellContext());
    editorCell.addEditorCell(createConstant_yx4xk1_a0());
    editorCell.addEditorCell(createProperty_yx4xk1_b0());
    editorCell.addEditorCell(createConstant_yx4xk1_c0());
    editorCell.addEditorCell(createRefNodeList_yx4xk1_d0());
    editorCell.addEditorCell(createConstant_yx4xk1_e0());
    editorCell.addEditorCell(createRefNode_yx4xk1_f0());
    return editorCell;
  }
  private EditorCell createConstant_yx4xk1_a0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "mindmap");
    editorCell.setCellId("Constant_yx4xk1_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_yx4xk1_b0() {
    CellProviderWithRole provider = new PropertyCellProvider(myNode, getEditorContext());
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(getEditorContext());
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(getEditorContext());
      return manager.createNodeRoleAttributeCell(attributeConcept, provider.getRoleAttributeKind(), editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_yx4xk1_c0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "with");
    editorCell.setCellId("Constant_yx4xk1_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNodeList_yx4xk1_d0() {
    AbstractCellListHandler handler = new Mindmap_EditorBuilder_a.markersListHandler_yx4xk1_d0(myNode, "markers", getEditorContext());
    EditorCell_Collection editorCell = handler.createCells(new CellLayout_Indent(), false);
    editorCell.setCellId("refNodeList_markers");
    editorCell.setRole(handler.getElementRole());
    return editorCell;
  }
  private static class markersListHandler_yx4xk1_d0 extends RefNodeListHandler {
    @NotNull
    private SNode myNode;

    public markersListHandler_yx4xk1_d0(SNode ownerNode, String childRole, EditorContext context) {
      super(ownerNode, childRole, context, false);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    public SNode createNodeToInsert(EditorContext editorContext) {
      return NodeFactoryManager.createNode(MetaAdapterFactory.getConcept(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f1297L, "MindMap.structure.Marker"), null, getNode(), getNode().getModel());
    }
    public EditorCell createNodeCell(SNode elementNode) {
      EditorCell elementCell = getUpdateSession().updateChildNodeCell(elementNode);
      installElementCellActions(elementNode, elementCell);
      return elementCell;
    }
    public EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(markersListHandler_yx4xk1_d0.this.getNode(), MetaAdapterFactory.getContainmentLink(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f127fL, 0x3d10348ce68f1b94L, "markers")));
      try {
        EditorCell emptyCell = null;
        emptyCell = super.createEmptyCell();
        installElementCellActions(null, emptyCell);
        setCellContext(emptyCell);
        return emptyCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    public void installElementCellActions(SNode elementNode, EditorCell elementCell) {
      if (elementCell.getUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET) == null) {
        elementCell.putUserObject(AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET, AbstractCellListHandler.ELEMENT_CELL_ACTIONS_SET);
        if (elementNode != null) {
          elementCell.setAction(CellActionType.DELETE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.FORWARD));
          elementCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteNode(elementNode, CellAction_DeleteNode.DeleteDirection.BACKWARD));
        }
        if (elementCell.getSubstituteInfo() == null || elementCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
          elementCell.setSubstituteInfo(new SChildSubstituteInfo(elementCell, getNode(), MetaAdapterFactory.getContainmentLink(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f127fL, 0x3d10348ce68f1b94L, "markers"), elementNode));
        }
      }
    }
  }
  private EditorCell createConstant_yx4xk1_e0() {
    EditorCell_Constant editorCell = new EditorCell_Constant(getEditorContext(), myNode, "about");
    editorCell.setCellId("Constant_yx4xk1_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_yx4xk1_f0() {
    SingleRoleCellProvider provider = new Mindmap_EditorBuilder_a.centralTopicSingleRoleHandler_yx4xk1_f0(myNode, MetaAdapterFactory.getContainmentLink(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f127fL, 0x3d10348ce68f12b1L, "centralTopic"), getEditorContext());
    return provider.createCell();
  }
  private static class centralTopicSingleRoleHandler_yx4xk1_f0 extends SingleRoleCellProvider {
    @NotNull
    private SNode myNode;

    public centralTopicSingleRoleHandler_yx4xk1_f0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(containmentLink, context);
      myNode = ownerNode;
    }

    @Override
    @NotNull
    public SNode getNode() {
      return myNode;
    }

    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = getUpdateSession().updateChildNodeCell(child);
      editorCell.setAction(CellActionType.DELETE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f127fL, 0x3d10348ce68f12b1L, "centralTopic"), child));
      editorCell.setAction(CellActionType.BACKSPACE, new CellAction_DeleteSmart(getNode(), MetaAdapterFactory.getContainmentLink(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f127fL, 0x3d10348ce68f12b1L, "centralTopic"), child));
      installCellInfo(child, editorCell);
      return editorCell;
    }



    private void installCellInfo(SNode child, EditorCell editorCell) {
      if (editorCell.getSubstituteInfo() == null || editorCell.getSubstituteInfo() instanceof DefaultSubstituteInfo) {
        editorCell.setSubstituteInfo(new SChildSubstituteInfo(editorCell, myNode, MetaAdapterFactory.getContainmentLink(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f127fL, 0x3d10348ce68f12b1L, "centralTopic"), child));
      }
      if (editorCell.getRole() == null) {
        editorCell.setRole("centralTopic");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      getCellFactory().pushCellContext();
      getCellFactory().setNodeLocation(new SNodeLocation.FromParentAndLink(getNode(), MetaAdapterFactory.getContainmentLink(0x8e85de6d521a4a74L, 0x94fc793b12682f6eL, 0x3d10348ce68f127fL, 0x3d10348ce68f12b1L, "centralTopic")));
      try {
        EditorCell editorCell = super.createEmptyCell();
        editorCell.setCellId("empty_centralTopic");
        installCellInfo(null, editorCell);
        setCellContext(editorCell);
        return editorCell;
      } finally {
        getCellFactory().popCellContext();
      }
    }
    protected String getNoTargetText() {
      return "<no centralTopic>";
    }
  }
}
